name: GitHub Pages

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install Bundler
        run:
          gem install bundler
           
      - name: Cache dependencies
        uses: actions/cache@
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install dependencies  # GHA runs 18.04 which has old libvips
        run: >
          curl -L 'https://github.com/libvips/libvips/releases/download/v8.13.3/vips-8.13.3.tar.gz' | tar xzf - &&
          cd vips-* &&
          ./configure --prefix=/usr &&
          make &&
          sudo make install

      - name: Install Ruby dependencies
        run: bundle install

      - name: Run Jekyll
        run: bundle exec jekyll build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site/
          cname: snaps.dnysgdnt.com
