name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches: [ dev ]  # or master, depending on your default branch name
  pull_request:
    branches: [ dev ]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          
      - name: Install dependencies  # GHA runs 18.04 which has old libvips
        run: >
            curl -L 'https://github.com/libvips/libvips/releases/download/v8.13.3/vips-8.13.3.tar.gz' | tar xzf - &&
            cd vips-* &&
            ./configure --prefix=/usr &&
            make &&
            sudo make install
  
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        if: github.event_name != 'pull_request'
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: _site  # The folder the Jekyll site is built to
