name: Build and deploy Jekyll site

on:
  push:
    branches: [ dev ]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Modified pre-build without sudo
          pre_build_commands: apt-get update && apt-get install -y libvips libvips-dev
